site_name: 'Documentation Template'
repo_url: https://github.com/harness-idp-sandbox/morningstar-erick-test-one
edit_uri: https://github.com/harness-idp-sandbox/morningstar-erick-test-one/blob/main/docs/index.md

nav:
  - Home: index.md

plugins:
  - techdocs-core